### PR TITLE
Supported Tukey's biweight in robustSmoothSpline.

### PR DESCRIPTION
**Pull request by LTLA**
In response to #14, though it might need some coercion to fit the existing coding style.

### CODE REVIEW

**Comment by LTLA** [comment]
Any thoughts @HenrikBengtsson? I couldn't figure out how to compile the documentation - for some reason it just wouldn't get `method=` into `usage`; so I just modified `robustSmoothSpline.Rd` directly.

**Comment by HenrikBengtsson** [comment]
Hi thxs for the bump. I got sidetracked and the this slipped (but did think about two days ago). I'll try to merge this during this week.

**Comment by HenrikBengtsson** [comment]
Forgot to explain how to compile Rdoc comments;
```sh
$ Rscript -e 'setwd("R"); library("aroma.light"); R.oo::Rdoc$compile()'
```
Package has to be re-installed before doing the above. Since roxygen2 is now supporting most of what Rdoc does, I'm slowly migrating, but until then the above is the way.  Also, `make Rd` does the same for all my packages.

**Comment by HenrikBengtsson** [comment]
So, with some minor tweaks to make it pass [`R CMD check --as-cran`](https://travis-ci.org/HenrikBengtsson/aroma.light/) and an added unit test, I've merged this into the [develop](https://github.com/HenrikBengtsson/aroma.light/tree/develop) branch (!= Bioc devel).  I'll soon try to push this up to Bioc.

Q. For [NEWS](https://github.com/HenrikBengtsson/aroma.light/blob/develop/NEWS#L10): Are you in the UK or at WEHI?

**Comment by LTLA** [comment]
Great, thanks. If needed, my affiliation is "CRUK Cambridge Institute". I use WEHI for my packages because that's what my BioC support site account uses, and BiocCheck complains if I'm not registered.

**Comment by HenrikBengtsson** [comment]
So, I just pushed to Bioc devel.

Now, I also did some naught when it comes this Git repository - I did `git push --force` of a somewhat different git tree.  **So, please delete your fork and re-fork.**   The reason why I did this was that the previous git tree in this repos was the main source which I need keep commit updates from to the then Bioconductor SVN server.  That was all fine.  Then Bioconductor migrated to Git and did their own SVN-to-git export, which does not match the one that used to be here.   Since they don't allow me to force push the existing Git tree I already had, I couldn't do much about it.  The content is basically the same through the history but some of the commit checksums no longer match up.

**Comment by LTLA** [comment]
Thanks, and will do.

**Pull request closed without merging**
